SELECT 
    KF.TABLE_NAME AS 'child_table',
    KF.COLUMN_NAME AS 'child_column',
    KP.TABLE_NAME AS 'parent_table',
    KP.COLUMN_NAME AS 'parent_column',
    KF.CONSTRAINT_NAME AS 'contraint'
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KF 
    ON C.CONSTRAINT_NAME = KF.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KP 
    ON C.UNIQUE_CONSTRAINT_NAME = KP.CONSTRAINT_NAME
ORDER BY KF.TABLE_NAME, KF.CONSTRAINT_NAME;