SELECT 
    KU.TABLE_NAME 'table',
    COLUMN_NAME 'column',
    KU.CONSTRAINT_NAME 'constraint'
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KU
    ON TC.CONSTRAINT_NAME = KU.CONSTRAINT_NAME
WHERE TC.CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY KU.TABLE_NAME, KU.CONSTRAINT_NAME;